<a href="https://colab.research.google.com/github/kgcibu/Coding-challenge/blob/Python/Machine%20learning%20%201.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

A=np.array([[1,2],[3,4]]);
B=np.array([[5,6],[7,8]]);
A101=A+B;
A102=A-B;
A103=B-A
A104=A*B;
A105=B*A;
F=np.dot(A,B);
T=np.transpose(A);
D=np.linalg.det(A);
I=np.linalg.inv(A);
R=np.linalg.matrix_rank(A);
E=np.linalg.eigvals(A);
C=np.array([5,11]);
X=np.linalg.solve(A,B)



print("Matrix addition:\n",A101);
print("Matrix Substraction is :\n",A102);
print("Matrix Substraction is :\n",A103);
print("Matrix Mutiplication is :\n",A104);
print("Matrix Mutiplication is :\n",A105);
print("Matrix dot product is :\n",F);
print("Transpose of A is :\n",T);
print("Determinant of A is :\n",D);
print("Inverse of A is :\n\n",I);
print("Rank of A is :\n\n",R);
print("Eigen values of A is :\n\n\n",E);

print("\n\nSOLUTION OF LINEAR SIMULTANEOUS EQUATION IN TWO VARIABLE IS  :\n\n",X);




Matrix addition:
 [[ 6  8]
 [10 12]]
Matrix Substraction is :
 [[-4 -4]
 [-4 -4]]
Matrix Substraction is :
 [[4 4]
 [4 4]]
Matrix Mutiplication is :
 [[ 5 12]
 [21 32]]
Matrix Mutiplication is :
 [[ 5 12]
 [21 32]]
Matrix dot product is :
 [[19 22]
 [43 50]]
Transpose of A is :
 [[1 3]
 [2 4]]
Determinant of A is :
 -2.0000000000000004
Inverse of A is :

 [[-2.   1. ]
 [ 1.5 -0.5]]
Rank of A is :

 2
Eigen values of A is :


 [-0.37228132  5.37228132]


SOLUTION OF LINEAR SIMULTANEOUS EQUATION IN TWO VARIABLE IS  :

 [[-3. -4.]
 [ 4.  5.]]
